version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: siema
      - POSTGRES_DB: portfolio_manager
    ports:
      - "5432:5432"