name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install flask flask_restful transformers peft torch flask_sqlalchemy psycopg2-binary

    - name: Wait for PostgreSQL to start
      run: dockerize -wait tcp://localhost:5432 -timeout 1m

    - name: Create test database
      run: |
        psql -h localhost -U postgres -c "CREATE DATABASE portfolio_manager_test;"

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/portfolio_manager_test
      run: python -m unittest discover
